logging:
  level:
    org.springframework.security: DEBUG
security:
  sessions: ALWAYS
  user:
    password: password
zuul:
  routes:
    ui:
      url: http://localhost:8081
      sensitive-headers:
    admin:
      url: http://localhost:8082
      sensitive-headers:
    resource:
      url: http://localhost:9000
      sensitive-headers:
spring:
  session:
    store-type: redis
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/todolist-users
    username: root
    password: 